trivia_app/config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :users, only: [ :show ] do
    resources :user_questions
  end
end

trivia_app/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :user_questions

  validates :body, presence: true
  validates :answer, presence: true
  validates  :options, presence: true

  def answers
    array = options << answer
    array.shuffle!
  end
end

trivia_app/app/models/question_grader.rb
class QuestionGrader
  attr_reader :soul, :query, :selection

  def initialize(soul, query, selection)
    @soul = soul
    @query = query
    @selection = selection
  end

  def grade
    if query.answer == selection
      true
    else
      false
    end
  end

  def attributes
    attrs = Hash.new
    attrs[:correct?] = grade
    attrs[:user_id] = soul.id
    attrs[:question_id] = query.id
    attrs[:response] = selection
    attrs
  end
end

trivia_app/app/models/quiz.rb
class Quiz
  include ActiveModel::Model
  attr_reader :array

  def initialize(array)
    @array = array
  end

  def date_taken
    array[0].created_at.strftime("%D %H:%M")
  end

  def right
    sum = 0
    array.each { |a| a.correct? ? sum += 1 : sum }
    sum
  end

  def percent_right
    '%.1f' % [(right / 5.0) * 100]
  end
end

trivia_app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

trivia_app/app/models/user_question.rb
class UserQuestion < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :response, presence: { allow_blank: true }

end

trivia_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  #
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :handle
  end
end

trivia_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    session[:count] = 1
    if current_user
      redirect_to user_user_questions_path(current_user)
    end
  end
end

trivia_app/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def show
  end

end

trivia_app/app/controllers/user_questions_controller.rb
require 'byebug'
require 'question_grader'
require 'quiz'

class UserQuestionsController < ApplicationController

  before_action :completed_quiz_check, only: [ :index ]

  def index
    @user_questions = UserQuestion.where(user_id: @user.id).to_a
    @quizzes = []
    while !@user_questions.empty?
      @quizzes << Quiz.new(@user_questions.slice!(0..4))
    end
  end

  def new
      @user = current_user
      @user_question = UserQuestion.new

      random_id = rand(1..Question.count)
      while UserQuestion.where(user_id: @user.id,
                               question_id: random_id,
                               "correct?": true).exists?
        puts random_id
        random_id = rand(Question.count)
      end

      @question = Question.find(random_id)
      session[:q] = @question.id
      @answers = @question.answers
      @user_question.response = params[:response]
  end

  def create
    session[:count] += 1
    @user = current_user
    @question = Question.find(session[:q])
    @answers = @question.answers
    grader = QuestionGrader.new(@user, @question, params[:response])
    @user_question = UserQuestion.create(grader.attributes)

    if grader.grade
      flash[:notice] = "Right-o!"
    else
      flash[:notice] = "Wrong!"
    end

    if session[:count] == 6
      session[:count] = 1
      redirect_to user_path(@user)
    else
      redirect_to :back
    end
  end


  protected
  def user_question_params
    params.require(:user_question).permit(:correct?, :response, :user_id,
                                          :question_id,)
  end

  def completed_quiz_check
    @user = current_user
    user_questions = UserQuestion.where(user_id: @user.id).to_a
    incomplete = user_questions.size % 5
    if incomplete > 0
      to_remove = user_questions.reverse.take(incomplete)
      to_remove.each do |question|
        question.delete
      end
    end
  end
end

trivia_app/app/controllers/users_controller.rb
#require 'byebug'

class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @user_questions = UserQuestion.where(user_id: params[:id])
  end

  protected
  def user_params
    params.require(:user).permit(:email, :password, :handle)
  end
end

trivia_app/app/views/homes/index.html.erb
<div class="row">
  <div class="medium-8 push-1 medium-centered columns">
    <h1 class="welcome">Five Questions Quick Trivia</h1>

    <p>
      Three spare minutes before the next meeting?  This site is for you!  'Sign
      In,' 'Start New Quiz' and take on just five squirrelly factoids to sharpen
      your brain before moving on with your day.
    </p>
    <p>
      *Login is required*, but only so we can provide your quiz history.  We do
      not track activity beyond this trivia site.
    </p>
  </div>
</div>

trivia_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TriviaApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="medium-2 columns">
      <ul class="side-nav">
        <br>
        <li><%= link_to "Fun Trivia", "http://www.funtrivia.com" %></li>
        <li><%= link_to "Trivia Playing", "http://www.triviaplaying.com" %></li>
        <li><%= link_to "Useful Trivia", "http://wwww.usefultrivia.com" %></li>
        <li><%= link_to "Trivia Plaza", "http://wwww.triviaplaza.com" %></li>

        <%- if current_user -%>
        <div class="log-links">
          <li ><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        </div>

        <%- else -%>
        <div class="log-links">
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
        </div>
        <%- end -%>
      </ul>
    </div>

    <div class="container">
      <div class="row">
        <div class="column">
          <%= yield %>
       </div>
     </div>
   </div>


  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

trivia_app/app/views/user_questions/index.html.erb
<div class="row">
  <div class="medium-8 push-2 medium-centered columns">
    <h1><%= @user.handle %>: Past Quizzes</h1>

    <%- if (@quizzes.size >= 1) -%>
      <table>
        <tr>
          <th>Date Taken</th>
          <th>Right Answers</th>
          <th>Percent Right Answers</th>
          <th></th>
        </tr>

        <%- @quizzes.each do |q| -%>
          <tr>
            <td><%= q.date_taken %></td>
            <td><%= q.right %></td>
            <td><%= q.percent_right %>%</td>
          </tr>
        <%- end -%>
      </table>
      <% else%>
       <div>Quiz history is empty.</div>
      <%- end -%>

      <div>
        <%= notice %>
      </div>

    <p class="menu">
      <%= link_to 'Start New Quiz', new_user_user_question_path(@user),
           method: :get %> | <%= link_to 'Home', root_path, method: :get %>
    </p>
  </div>
</div>

trivia_app/app/views/user_questions/new.html.erb
<div class="row">
  <div class="medium-8 push-3">
    <div class="card">

      <p id="question-num">Question <%= (session[:count]) %> of 5</p>
      <p id="question-body"><%= @question.body %></p>

      <%= form_tag "/users/#{@user.id}/user_questions" do %>

        <%= radio_button_tag :response, @answers[0] %>
        <%= label_tag :response_zero, @answers[0] %><br>
        <%= radio_button_tag :response, @answers[1] %>
        <%= label_tag :response_one, @answers[1] %><br>
        <%= radio_button_tag :response, @answers[2] %>
        <%= label_tag :response_two, @answers[2] %><br>
        <%= radio_button_tag :response, @answers[3] %>
        <%= label_tag :response_three, @answers[3] %><br>

        <%= submit_tag "Submit" %>
      <% end %>
    </div>
    <%= notice %>
  </div>
</div>

trivia_app/app/views/users/show.html.erb
<div class="row">
<div class="medium-8 columns">

<h1><%= @user.handle %>, you finished a quiz!</h1>

  <p><%= link_to 'Start New Quiz', new_user_user_question_path(@user),
         method: :get %> |
  <%= link_to 'User Home', user_user_questions_path(@user), method: :get %>
  </p>
</div>
</div>